// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDysg9OeqPTwE16qiv_bRRUpHQBTQePMkU',
    appId: '1:551329935597:ios:8e67f08758512070801ce4',
    messagingSenderId: '551329935597',
    projectId: 'dazzle-fashion-ef4c1',
    storageBucket: 'dazzle-fashion-ef4c1.firebasestorage.app',
    iosBundleId: 'com.example.dazzleApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9Qx33zlPnMkHLBeLZanrvdsC0QZfV8U',
    appId: '1:551329935597:android:55afa6b557bf0aa5801ce4',
    messagingSenderId: '551329935597',
    projectId: 'dazzle-fashion-ef4c1',
    storageBucket: 'dazzle-fashion-ef4c1.firebasestorage.app',
  );

}